# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122WORRoMgM3tHkc9OdN4B3rrwrdDZZH1
"""

# =========================================================
# MONEY, HAPPINESS & QUALITY OF LIFE ANALYTICS PROJECT
# =========================================================

# =========================
# IMPORT LIBRARIES
# =========================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# =========================
# LOAD DATASETS
# =========================

h2015 = pd.read_csv("/content/2015.csv")
h2016 = pd.read_csv("/content/2016.csv")
h2017 = pd.read_csv("/content/2017.csv")
h2018 = pd.read_csv("/content/2018.csv")
h2019 = pd.read_csv("/content/2019.csv")

employee = pd.read_csv("/content/Employee Attrition.csv")

cost1 = pd.read_csv("/content/cost-of-living.csv")
cost2 = pd.read_csv("/content/cost-of-living_v2.csv")

# =========================
# ADD YEAR COLUMN
# =========================

h2015["Year"] = 2015
h2016["Year"] = 2016
h2017["Year"] = 2017
h2018["Year"] = 2018
h2019["Year"] = 2019

# =========================
# STANDARDIZE COLUMN NAMES
# =========================

def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
        .str.replace(".", "_")
    )
    return df

h2015 = clean_columns(h2015)
h2016 = clean_columns(h2016)
h2017 = clean_columns(h2017)
h2018 = clean_columns(h2018)
h2019 = clean_columns(h2019)

employee = clean_columns(employee)
cost1 = clean_columns(cost1)
cost2 = clean_columns(cost2)

# =========================
# DISPLAY COLUMNS
# =========================

print(h2015.columns)
print(h2016.columns)
print(h2017.columns)
print(h2018.columns)
print(h2019.columns)

# =========================
# STANDARDIZE HAPPINESS DATA
# =========================

def standardize_happiness(df):

    rename_dict = {}

    for col in df.columns:

        if "country" in col:
            rename_dict[col] = "country"

        elif "score" in col:
            rename_dict[col] = "happiness_score"

        elif "gdp" in col:
            rename_dict[col] = "gdp_per_capita"

        elif "family" in col or "social_support" in col:
            rename_dict[col] = "social_support"

        elif "health" in col:
            rename_dict[col] = "healthy_life_expectancy"

        elif "freedom" in col:
            rename_dict[col] = "freedom"

        elif "corruption" in col or "trust" in col:
            rename_dict[col] = "trust"

        elif "generosity" in col:
            rename_dict[col] = "generosity"

    df = df.rename(columns=rename_dict)

    return df

h2015 = standardize_happiness(h2015)
h2016 = standardize_happiness(h2016)
h2017 = standardize_happiness(h2017)
h2018 = standardize_happiness(h2018)
h2019 = standardize_happiness(h2019)

# =========================
# COMBINE HAPPINESS DATA
# =========================

happiness = pd.concat([
    h2015,
    h2016,
    h2017,
    h2018,
    h2019
], ignore_index=True)

# =========================
# KEEP IMPORTANT COLUMNS
# =========================

keep_cols = [
    "country",
    "year",
    "happiness_score",
    "gdp_per_capita",
    "social_support",
    "healthy_life_expectancy",
    "freedom",
    "generosity",
    "trust"
]

existing_cols = [c for c in keep_cols if c in happiness.columns]

happiness = happiness[existing_cols]

# =========================
# BASIC CLEANING
# =========================

happiness = happiness.dropna()

# =========================
# OVERVIEW
# =========================

print(happiness.shape)

display(happiness.head())

# =========================
# DESCRIPTIVE STATISTICS
# =========================

display(happiness.describe())

# =========================
# TOP HAPPIEST COUNTRIES
# =========================

top_happy = (
    happiness.groupby("country")["happiness_score"]
    .mean()
    .sort_values(ascending=False)
    .head(15)
)

display(top_happy)

# =========================
# VISUALIZATION
# =========================

plt.figure(figsize=(10,6))

top_happy.sort_values().plot(kind="barh")

plt.title("Top Happiest Countries")
plt.xlabel("Average Happiness Score")

plt.show()

# =========================
# GDP VS HAPPINESS
# =========================

plt.figure(figsize=(8,6))

plt.scatter(
    happiness["gdp_per_capita"],
    happiness["happiness_score"],
    alpha=0.6
)

plt.xlabel("GDP Per Capita")
plt.ylabel("Happiness Score")
plt.title("GDP vs Happiness")

plt.show()

# =========================
# CORRELATION MATRIX
# =========================

numeric_cols = happiness.select_dtypes(include=np.number)

corr = numeric_cols.corr()

display(corr)

# =========================
# MOST IMPORTANT FACTORS
# =========================

corr_target = (
    corr["happiness_score"]
    .sort_values(ascending=False)
)

display(corr_target)

# =========================
# FEATURE ENGINEERING
# =========================

happiness["wealth_freedom_score"] = (
    happiness["gdp_per_capita"] *
    happiness["freedom"]
)

happiness["support_health_score"] = (
    happiness["social_support"] *
    happiness["healthy_life_expectancy"]
)

# =========================
# PREDICTIVE MODEL
# =========================

features = [
    "gdp_per_capita",
    "social_support",
    "healthy_life_expectancy",
    "freedom",
    "generosity",
    "trust",
    "wealth_freedom_score",
    "support_health_score"
]

features = [f for f in features if f in happiness.columns]

X = happiness[features]

y = happiness["happiness_score"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

preds = model.predict(X_test)

# =========================
# MODEL PERFORMANCE
# =========================

print("R2 Score:", r2_score(y_test, preds))
print("MAE:", mean_absolute_error(y_test, preds))

# =========================
# FEATURE IMPORTANCE
# =========================

importance = pd.DataFrame({
    "Feature": features,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    "Importance",
    ascending=False
)

display(importance)

# =========================
# FEATURE IMPORTANCE CHART
# =========================

plt.figure(figsize=(10,6))

plt.barh(
    importance["Feature"],
    importance["Importance"]
)

plt.title("Factors Predicting Happiness")

plt.xlabel("Importance")

plt.show()

# =========================
# COUNTRY TREND ANALYSIS
# =========================

country_trends = (
    happiness.groupby(["year"])["happiness_score"]
    .mean()
)

display(country_trends)

# =========================
# TREND VISUALIZATION
# =========================

plt.figure(figsize=(8,5))

country_trends.plot(marker="o")

plt.title("Average Global Happiness Over Time")

plt.ylabel("Happiness Score")
plt.xlabel("Year")

plt.grid(True)

plt.show()

# =========================
# FINAL INSIGHTS
# =========================

print("\nPROJECT INSIGHTS")
print("========================")

print("\n1. GDP alone does not fully predict happiness.")

print("\n2. Social support and freedom appear strongly associated with higher happiness.")

print("\n3. Countries with stronger support systems consistently rank higher.")

print("\n4. Happiness appears influenced by multiple interacting economic and behavioral factors.")

print("\n5. Wealth combined with autonomy predicts happiness better than wealth alone.")

# =========================
# EXPORT CLEANED DATA
# =========================

happiness.to_csv(
    "/content/final_happiness_dataset.csv",
    index=False
)

print("\nSaved final_happiness_dataset.csv")